services:
  - type: pserv
    name: mysql-db
    env: docker
    disk:
      name: mysql-disk
      mountPath: /var/lib/mysql
      sizeGB: 10
    dockerfilePath: Salary Record/mysql/Dockerfile
    buildCommand: ""
    startCommand: "docker-entrypoint.sh mysqld"
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: "your_strong_password"
      - key: MYSQL_DATABASE
        value: "psm"

  - type: web
    name: psms-api
    env: docker
    dockerfilePath: Salary Record/api/Dockerfile
    buildCommand: ""
    startCommand: "node app.js"
    envVars:
      - key: MYSQL_HOST
        fromService:
          name: mysql-db
          type: pserv
          property: host
      - key: MYSQL_USER
        value: "root"
      - key: MYSQL_PASSWORD
        value: "your_strong_password"
      - key: MYSQL_DATABASE
        value: "psm"
      - key: PORT
        value: "4000"
